### ISSUE TITLE
加入修改 user-rule 自动更新 pac 的功能

### ISSUE THREAD

**Issue by everyx** [everyx/shadowsocks-csharp#1]

**Comment by LazyZhu** [comment]
上游更新了,可以同步下吗?

**Comment by everyx** [comment]
好的，我下周合并一下，谢谢提醒

LazyZhu <notifications@github.com>于2015年7月12日周日 11:30写道：

**Comment by everyx** [comment]
你好，更新到上有最新版本的代码了，还没怎么测试，用着没啥问题，拖到现在，抱歉啦，如果要下载的话，请到我这个项目主页的 release 标签里面找下载地址

**Comment by LazyZhu** [comment]
@everyx Thanks.
